version: '3'

services:
  db:
    build: /db/.
    ports:
      - "27017:27017"

  calculator:
    build: /html/.
    ports:
      - "80"
    restart: always
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mdc.rule=Host(`mdc.examle.com`)"
      - "traefik.http.services.mdc.loadbalancer.server.port=80"
      - "traefik.http.routers.mdc.tls.certresolver=le"
      - "traefik.http.middlewares.mdc.redirectscheme.scheme=https"
      - "traefik.http.middlewares.mdc.redirectscheme.permanent=true"
networks:
  traefik-proxy:
    external: true